services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - api-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=./data/juju-aviatrice.sqlite
      - CORS_ORIGIN=https://app.juju-aviatrice.uk
    restart: always

volumes:
  api-data:
